### PR TITLE
fix cucumberjs reporter on windows

### LINKED ISSUE #492: Cannot run scenario after update to 2.0.0-beta.19
Hello there. I have been using beta 18 for running my tests and it runs fine. However when I update the package to beta 19 and start running the first scenario it's showing the error down below. Any idea what's going on?

node v16.17.0
npm 8.15.0

```
TypeError: process_1.default.getuid is not a function
    at CucumberJSAllureFormatter.onTestCaseStarted (..\node_modules\allure-cucumberjs\src\CucumberJSAllureReporter.ts:242:75)
    at CucumberJSAllureFormatter.parseEnvelope (..\node_modules\allure-cucumberjs\src\CucumberJSAllureReporter.ts:119:12)
    at EventEmitter.emit (node:events:532:35)
    at EventEmitter.emit (node:domain:475:12)
```

### PR DESCRIPTION
**Pull request by lamartire**
### Context
fixes #492

Use `process.pid` as fallback value for `THREAD` label

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

File: packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts [hunk 1]
```diff
@@ -232,17 +232,21 @@ export class CucumberJSAllureFormatter extends Formatter {
     const labels = this.parseTagsLabels(scenario?.tags || []);
     const links = this.parseTagsLinks(scenario?.tags || []);
     const currentTest = new AllureTest(this.allureRuntime, Date.now());
+    const thread = ALLURE_THREAD_NAME || process?.getuid()?.toString();
```
Comment (vovsemenv) [inline packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts:235]: maybe  we can use `process.pid` for compatibility

**Review by vovsemenv — CHANGES_REQUESTED** [review]

File: packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts (hunk 1 above)
Comment (lamartire) [reply packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts:235]: Why not, good catch

File: packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts [hunk 2]
```diff
@@ -232,16 +232,17 @@ export class CucumberJSAllureFormatter extends Formatter {
     const labels = this.parseTagsLabels(scenario?.tags || []);
     const links = this.parseTagsLinks(scenario?.tags || []);
     const currentTest = new AllureTest(this.allureRuntime, Date.now());
+    const thread = ALLURE_THREAD_NAME || process?.getuid()?.toString() || process.pid.toString();
```
Comment (vovsemenv) [inline packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts:235]: I think we should completely switch to `procces.pid` and drop `getuid`

Comment (lamartire) [reply packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts:235]: `uid` and `pid` are different things, but yes, better to keep on thing here

Comment (vovsemenv) [reply packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts]: i think uid don't make sense in that case.

Comment (vovsemenv) [reply packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts]: when we wank to mark `process id` not `user id`

**Review by vovsemenv — APPROVED** [review]
Ok, it works.

But thread labels isn't right. Currently just mark all tests with current reporter process. Need worker Id from cucumber team i guess.

image

**Review by baev — APPROVED** [review]
