### ISSUE TITLE
Cannot run scenario after update to 2.0.0-beta.19

### ISSUE THREAD

**Issue by ooo2003003v2** [allure-framework/allure-js#492]
Hello there. I have been using beta 18 for running my tests and it runs fine. However when I update the package to beta 19 and start running the first scenario it's showing the error down below. Any idea what's going on?

node v16.17.0
npm 8.15.0

```
TypeError: process_1.default.getuid is not a function
    at CucumberJSAllureFormatter.onTestCaseStarted (..\node_modules\allure-cucumberjs\src\CucumberJSAllureReporter.ts:242:75)
    at CucumberJSAllureFormatter.parseEnvelope (..\node_modules\allure-cucumberjs\src\CucumberJSAllureReporter.ts:119:12)
    at EventEmitter.emit (node:events:532:35)
    at EventEmitter.emit (node:domain:475:12)
```

**Comment by AlexandrShlyaeu** [comment]
<img width="878" alt="image" src="https://user-images.githubusercontent.com/22616306/188475695-97b9db09-73e1-4495-879e-5615cbf421fa.png">
