### ISSUE TITLE
[allure-cypress] TypeError: t.attributes.renderProps is not a function

### ISSUE THREAD

**Issue by Ferdidurke** [allure-framework/allure-js#1280]
**Describe the bug**
After updating the version to 3.0.7 and higher (up to the current 3.2.1), e2e tests using cypress stopped running on my project. I am seeing the following error:
```
index.js:1 Uncaught TypeError: t.attributes.renderProps is not a function
    at ts (index.js:1:20087)
    at Te (index.js:1:19514)
    at $Cypress.cs (index.js:1:21187)
    at EventEmitter.emit (cypress_runner.js:143295:22)
    at parent.<computed> [as emit] (cypress_runner.js:142171:31)
    at $Cypress.action (cypress_runner.js:41609:21)
    at LogManager.trigger (cypress_runner.js:131214:22)
    at LogManager.triggerLog (cypress_runner.js:131219:17)
    at $Cypress.log (cypress_runner.js:131271:12)
    at PrimaryOriginCommunicator.<anonymous> (index-DHbNdp46.js:5413:124059)
```

After reviewing the source code, I assume the problem is that the function is not defined at this location, but is still called - https://github.com/allure-framework/allure-js/compare/v3.0.6...v3.0.7#diff-7dd2ec1ebdabb86fa3c17e789cb1f5a32e21edcff150c8cf373a479dc7957c29R118
I think optional chaning operator must be checked before function call

**To Reproduce**
My package.json
```
 "dependencies": {
    "@auth0/auth0-react": "2.3.0",
    "@tanstack/react-query": "5.72.2",
    "@tanstack/react-table": "8.21.2",
    "axios": "1.8.4",
    "classnames": "2.5.1",
    "dayjs": "1.11.13",
    "formik": "2.4.6",
    "fs-extra": "11.3.0",
    "jwt-decode": "4.0.0",
    "react": "19.1.0",
    "react-bootstrap": "2.10.9",
    "react-datepicker": "8.3.0",
    "react-dom": "19.1.0",
    "react-inlinesvg": "4.2.0",
    "react-number-format": "5.4.3",
    "react-router": "7.5.0",
    "react-select": "5.10.1",
    "react-toastify": "11.0.5",
    "yup": "1.6.1"
  },
  "devDependencies": {
    "@cypress/code-coverage": "3.14.0",
    "@cypress/react": "9.0.1",
    "@eslint/js": "9.24.0",
    "@istanbuljs/nyc-config-typescript": "1.0.2",
    "@tanstack/eslint-plugin-query": "5.72.2",
    "@tanstack/react-query-devtools": "5.72.2",
    "@testing-library/dom": "10.4.0",
    "@testing-library/jest-dom": "6.6.3",
    "@testing-library/react": "16.3.0",
    "@testing-library/user-event": "14.6.1",
    "@types/node": "22.14.0",
    "@types/react": "19.1.0",
    "@types/react-dom": "19.1.2",
    "@vitejs/plugin-react": "4.3.4",
    "@vitest/coverage-istanbul": "3.1.1",
    "allure-commandline": "2.33.0",
    "allure-cypress": "3.2.1",
    "cypress": "14.3.0",
    "cypress-multi-reporters": "2.0.5",
    "cypress-parallel": "0.15.0",
    "dotenv": "16.4.7",
    "eslint": "9.24.0",
    "eslint-config-prettier": "10.1.1",
    "eslint-import-resolver-alias": "1.1.2",
    "eslint-import-resolver-typescript": "4.3.2",
    "eslint-plugin-cypress": "4.2.1",
    "eslint-plugin-import": "2.31.0",
    "eslint-plugin-prettier": "5.2.6",
    "eslint-plugin-react": "7.37.5",
    "eslint-plugin-react-hooks": "5.2.0",
    "globals": "16.0.0",
    "husky": "9.1.7",
    "jsdom": "26.0.0",
    "lint-staged": "15.5.0",
    "prettier": "3.5.3",
    "sass": "1.86.3",
    "serve": "14.2.4",
    "start-server-and-test": "2.0.11",
    "typescript": "5.8.3",
    "typescript-eslint": "8.29.1",
    "vite": "6.2.5",
    "vite-plugin-istanbul": "7.0.0",
    "vitest": "3.1.1"
  },
```

**Expected behavior**
E2E-tests continue works

**Screenshots**

![Image](https://github.com/user-attachments/assets/1eb5bbd8-a366-4c2d-9614-eac6678c71dc)

**Desktop (please complete the following information):**
 - OS: MacOS 15.3.2 (don't think it's important)

**Additional context**

**Comment by koreyba** [comment]
It didn't happen on Cypress 13.7.0, I've updated to 14.1.1 and it started happening.

**Comment by todti** [comment]
@koreyba H! I'm still working on this issue and will try to fix it asap. There might be cases involving more than just this function.

Could you provide an example of your test where the error definitely occurs please? Replace any sensitive information with placeholders.
